[build]
  base    = "website"
  publish = "build"
  command = "npm run netlify-build  && cp _redirects ./build"
  ignore = "git diff --quiet HEAD^ HEAD docs website"

[build.environment]
NODE_VERSION = "14"

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [
      "node_modules/.cache",
    ]